<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-21T10:54:34 IST" name="Default suite" finished-at="2021-04-21T10:57:06 IST" duration-ms="151999">
    <groups>
    </groups>
    <test started-at="2021-04-21T10:54:34 IST" name="Default test" finished-at="2021-04-21T10:57:06 IST" duration-ms="151999">
      <class name="com.athmatest.qa.testcases.SampleTest">
        <test-method is-config="true" signature="intialization()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:54:34 IST" name="intialization" finished-at="2021-04-21T10:54:55 IST" duration-ms="21047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intialization -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:54:55 IST" name="loginToTheApplication" finished-at="2021-04-21T10:55:01 IST" duration-ms="6330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myFirstTest()[pri:1, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:55:01 IST" name="myFirstTest" finished-at="2021-04-21T10:55:01 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFirstTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:55:01 IST" name="logOutFromTheApplication" finished-at="2021-04-21T10:55:19 IST" duration-ms="18468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:55:19 IST" name="loginToTheApplication" finished-at="2021-04-21T10:55:26 IST" duration-ms="6274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="mySecondTest()[pri:2, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:55:26 IST" name="mySecondTest" finished-at="2021-04-21T10:55:51 IST" duration-ms="25553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySecondTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:55:51 IST" name="logOutFromTheApplication" finished-at="2021-04-21T10:56:04 IST" duration-ms="12627" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:04 IST" name="loginToTheApplication" finished-at="2021-04-21T10:56:10 IST" duration-ms="6294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myThirdTest()[pri:3, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:10 IST" name="myThirdTest" finished-at="2021-04-21T10:56:19 IST" duration-ms="9221" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.athmatest.qa.testcases.SampleTest.myThirdTest(SampleTest.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myThirdTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:20 IST" name="logOutFromTheApplication" finished-at="2021-04-21T10:56:26 IST" duration-ms="6289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="loginToTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:26 IST" name="loginToTheApplication" finished-at="2021-04-21T10:56:32 IST" duration-ms="6302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToTheApplication -->
        <test-method signature="myFourthTest()[pri:4, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:32 IST" name="myFourthTest" finished-at="2021-04-21T10:56:41 IST" duration-ms="8435" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.athmatest.qa.testcases.SampleTest.myFourthTest(SampleTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myFourthTest -->
        <test-method is-config="true" signature="logOutFromTheApplication()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:56:41 IST" name="logOutFromTheApplication" finished-at="2021-04-21T10:57:05 IST" duration-ms="23816" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutFromTheApplication -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.athmatest.qa.testcases.SampleTest@dd8ba08]" started-at="2021-04-21T10:57:05 IST" name="closeBrowser" finished-at="2021-04-21T10:57:06 IST" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.athmatest.qa.testcases.SampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
